In [1]:
import pandas as pd

In [2]:
data=pd.read_csv(r'passwords.csv',error_bad_lines=False)

C:\Users\lomes\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
b'Skipping line 2810: expected 2 fields, saw 5\nSkipping line 4641: expected 2 fields, saw 5\nSkipping line 7171: expected 2 fields, saw 5\nSkipping line 11220: expected 2 fields, saw 5\nSkipping line 13809: expected 2 fields, saw 5\nSkipping line 14132: expected 2 fields, saw 5\nSkipping line 14293: expected 2 fields, saw 5\nSkipping line 14865: expected 2 fields, saw 5\nSkipping line 17419: expected 2 fields, saw 5\nSkipping line 22801: expected 2 fields, saw 5\nSkipping line 25001: expected 2 fields, saw 5\nSkipping line 26603: expected 2 fields, saw 5\nSkipping line 26742: expected 2 fields, saw 5\nSkipping line 29702: expected 2 fields, saw 5\nSkipping line 32767: expected 2 fields, saw 5\nSkipping line 32878: expected 2 fields, saw 5\nSkipping

b'Skipping line 525174: expected 2 fields, saw 5\nSkipping line 526251: expected 2 fields, saw 5\nSkipping line 529611: expected 2 fields, saw 5\nSkipping line 531398: expected 2 fields, saw 5\nSkipping line 534146: expected 2 fields, saw 5\nSkipping line 544954: expected 2 fields, saw 5\nSkipping line 553002: expected 2 fields, saw 5\nSkipping line 553883: expected 2 fields, saw 5\nSkipping line 553887: expected 2 fields, saw 5\nSkipping line 553915: expected 2 fields, saw 5\nSkipping line 554172: expected 2 fields, saw 5\nSkipping line 563534: expected 2 fields, saw 5\nSkipping line 565191: expected 2 fields, saw 5\nSkipping line 574108: expected 2 fields, saw 5\nSkipping line 574412: expected 2 fields, saw 5\nSkipping line 575985: expected 2 fields, saw 5\nSkipping line 580091: expected 2 fields, saw 5\nSkipping line 582682: expected 2 fields, saw 5\nSkipping line 585885: expected 2 fields, saw 5\nSkipping line 590171: expected 2 fields, saw 5\nSkipping line 591924: expected 2 field

In [3]:
data.head()

password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

In [4]:
len(data)

669640

In [5]:
data

password  strength
0           kzde5577         1
1           kino3434         1
2          visi7k1yr         1
3           megzy123         1
4        lamborghin1         1
...              ...       ...
669635    10redtux10         1
669636     infrared1         1
669637  184520socram         1
669638     marken22a         1
669639      fxx4pw4g         1

[669640 rows x 2 columns]

In [6]:
data.isnull().sum()

password    1
strength    0
dtype: int64

In [7]:
data.dropna(inplace=True)

In [8]:
data=data.reset_index()

In [9]:
data

index      password  strength
0            0      kzde5577         1
1            1      kino3434         1
2            2     visi7k1yr         1
3            3      megzy123         1
4            4   lamborghin1         1
...        ...           ...       ...
669634  669635    10redtux10         1
669635  669636     infrared1         1
669636  669637  184520socram         1
669637  669638     marken22a         1
669638  669639      fxx4pw4g         1

[669639 rows x 3 columns]

In [10]:
data.drop(columns=['index'],inplace=True)

In [11]:
data.strength.value_counts()

1    496801
0     89701
2     83137
Name: strength, dtype: int64

In [12]:
data.head(20)

password  strength
0           kzde5577         1
1           kino3434         1
2          visi7k1yr         1
3           megzy123         1
4        lamborghin1         1
5   AVYq1lDE4MgAZfNt         2
6           u6c8vhow         1
7           v1118714         1
8       universe2908         1
9           as326159         1
10          asv5o9yu         1
11      612035180tok         1
12        jytifok873         1
13  WUt9IZzE0OQ7PkNE         2
14      jerusalem393         1
15        g067057895         1
16       52558000aaa         1
17          idofo673         1
18         6975038lp         1
19         sbl571017         1

In [13]:
import random
import numpy as np

In [14]:
vect_data=np.array(data)

In [15]:
vect_data

array([['kzde5577', 1],
       ['kino3434', 1],
       ['visi7k1yr', 1],
       ...,
       ['184520socram', 1],
       ['marken22a', 1],
       ['fxx4pw4g', 1]], dtype=object)

In [16]:
random.shuffle(vect_data)

In [17]:
vect_data

array([['kzde5577', 1],
       ['kzde5577', 1],
       ['kzde5577', 1],
       ...,
       ['io3ze7t', 0],
       ['kctuwbavl3', 1],
       ['noucha1', 0]], dtype=object)

In [18]:
X=[columns[0] for columns in vect_data]

In [19]:
y=[columns[1] for columns in vect_data]

In [20]:
X,y

(['kzde5577',
  'kzde5577',
  'kzde5577',
  'kino3434',
  'visi7k1yr',
  'AVYq1lDE4MgAZfNt',
  'u6c8vhow',
  'u6c8vhow',
  'v1118714',
  'kzde5577',
  'asv5o9yu',
  'as326159',
  'universe2908',
  'megzy123',
  'jytifok873',
  'lamborghin1',
  'asv5o9yu',
  'g067057895',
  'WUt9IZzE0OQ7PkNE',
  'kzde5577',
  'as326159',
  'universe2908',
  'megzy123',
  '6975038lp',
  'intel1',
  'faranumar91',
  '0169395484a',
  'lamborghin1',
  'idofo673',
  'u6c8vhow',
  'AVYq1lDE4MgAZfNt',
  'sbl571017',
  'sbl571017',
  '6975038lp',
  'lamborghin1',
  'jytifok873',
  'visi7k1yr',
  'gaymaids1',
  'idofo673',
  '52558000aaa',
  'fahad123',
  '0169395484a',
  'intel1',
  'trabajonet9',
  'v1118714',
  'yitbos77',
  'schalke04',
  'lamborghin1',
  'schalke04',
  'asv5o9yu',
  'megzy123',
  'v1118714',
  'exitos2009',
  'schalke04',
  'a2531106',
  'lamborghin1',
  'ok>bdk',
  'TyWM72UNEex8Q8Y',
  'kzde5577',
  'matiofox08',
  'visi7k1yr',
  'sknq7m0',
  'kswa2mrv',
  'yitbos77',
  'c3h8bkzr',
  'jyti

In [21]:
data.shape

(669639, 2)

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
def word_to_char(word):
    char=[]
    for letter in word:
        char.append(letter)
    return char    

In [24]:
vectoriser=TfidfVectorizer(tokenizer=word_to_char)

In [25]:
train=vectoriser.fit_transform(X)

In [26]:
vectoriser.vocabulary_

{'k': 60,
 'z': 75,
 'd': 53,
 'e': 54,
 '5': 33,
 '7': 35,
 'i': 58,
 'n': 63,
 'o': 64,
 '3': 31,
 '4': 32,
 'v': 71,
 's': 68,
 '1': 29,
 'y': 74,
 'r': 67,
 'a': 50,
 'q': 66,
 'l': 61,
 'm': 62,
 'g': 56,
 'f': 55,
 't': 69,
 'u': 70,
 '6': 34,
 'c': 52,
 '8': 36,
 'h': 57,
 'w': 72,
 '9': 37,
 '2': 30,
 '0': 28,
 'j': 59,
 'b': 51,
 'p': 65,
 'x': 73,
 '>': 41,
 '!': 15,
 '.': 26,
 '&': 20,
 '?': 42,
 '<': 39,
 '@': 43,
 '-': 25,
 '_': 48,
 ';': 38,
 '±': 88,
 ' ': 14,
 '#': 17,
 '(': 21,
 ')': 22,
 '*': 23,
 '$': 18,
 '%': 19,
 '{': 76,
 '}': 78,
 '+': 24,
 '`': 49,
 '"': 16,
 '~': 79,
 '^': 47,
 '/': 27,
 'ô': 115,
 '\\': 45,
 '=': 40,
 '[': 44,
 ']': 46,
 '\x16': 8,
 'ó': 114,
 'ò': 113,
 '·': 93,
 '\x1e': 13,
 'þ': 124,
 '³': 90,
 'ú': 120,
 '\x19': 10,
 'ä': 103,
 'ð': 111,
 'å': 104,
 'â': 101,
 '|': 77,
 '«': 85,
 '´': 91,
 '\x1c': 12,
 '¿': 97,
 '\x05': 1,
 '\x1b': 11,
 'à': 99,
 '°': 87,
 'ß': 98,
 '¾': 96,
 'ÿ': 125,
 'á': 100,
 'º': 94,
 '¡': 82,
 '\x10': 5,
 '\x17': 9

In [27]:
train.shape

(669639, 127)

In [28]:
vectoriser.get_feature_names()

['\x01',
 '\x05',
 '\x06',
 '\x08',
 '\x0f',
 '\x10',
 '\x11',
 '\x12',
 '\x16',
 '\x17',
 '\x19',
 '\x1b',
 '\x1c',
 '\x1e',
 ' ',
 '!',
 '"',
 '#',
 '$',
 '%',
 '&',
 '(',
 ')',
 '*',
 '+',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '{',
 '|',
 '}',
 '~',
 '\x81',
 '\x8d',
 '¡',
 '¦',
 '¨',
 '«',
 '¯',
 '°',
 '±',
 '²',
 '³',
 '´',
 'µ',
 '·',
 'º',
 '¼',
 '¾',
 '¿',
 'ß',
 'à',
 'á',
 'â',
 'ã',
 'ä',
 'å',
 'æ',
 'ç',
 'é',
 'ê',
 'í',
 'ï',
 'ð',
 'ñ',
 'ò',
 'ó',
 'ô',
 'õ',
 'ö',
 '÷',
 'ù',
 'ú',
 'û',
 'ü',
 'ý',
 'þ',
 'ÿ',
 '—']

In [29]:
train.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [30]:
train

<669639x127 sparse matrix of type '<class 'numpy.float64'>'
	with 5647197 stored elements in Compressed Sparse Row format>

In [31]:
train[1].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.56687328, 0.        ,
        0.59201991, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.28578334, 0.22130493,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.29161481, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [32]:
train[0].toarray()


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.56687328, 0.        ,
        0.59201991, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.28578334, 0.22130493,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.29161481, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [33]:
from sklearn.metrics import accuracy_score

# Logistic Regression Model


In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(train,y,test_size=0.2,random_state=42)
log_classifier=LogisticRegression(multi_class='ovr')
log_classifier.fit(X_train,y_train)

C:\Users\lomes\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\lomes\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

LogisticRegression(multi_class='ovr')

In [35]:
log_classifier.score(X_test,y_test)

0.8121005316289349

In [36]:
y_pred_log=log_classifier.predict(X_test)
print(accuracy_score(y_test,y_pred_log))

0.8121005316289349


# Naive Bayes Model- Multinomial

In [37]:
from sklearn.naive_bayes import MultinomialNB
bayes_calssifier=MultinomialNB()
bayes_calssifier.fit(X_train,y_train)

MultinomialNB()

In [38]:
bayes_calssifier.score(X_test,y_test)

0.7428245027178783

# Multinomial-Logistic Regression Model 

In [39]:
multi_log_classifier=LogisticRegression(multi_class='multinomial',solver='newton-cg')
multi_log_classifier.fit(X_train,y_train)

LogisticRegression(multi_class='multinomial', solver='newton-cg')

In [40]:
multi_log_classifier.score(X_test,y_test)

0.8202690998148259

In [41]:
input_=np.array(["%@123abcd"])
input_=vectoriser.transform(input_)
y_pred=multi_log_classifier.predict(input_)
print(y_pred)

[1]


In [51]:
'''import pickle
with open('model_pickle.pkl','wb') as file:
    pickle.dump(multi_log_classifier,file)'''

In [52]:
'''with open('vectoriser_pickle.pkl','wb') as file:
    pickle.dump(vectoriser,file)'''

In [50]:
'''import pickle
with open('model_pickle','rb') as file:
    model=pickle.load(file)'''

In [46]:
'''with open('vectoriser_pickle','rb') as file:
    vectorissser=pickle.load(file)'''

In [48]:
print(model.predict(vectorissser.transform(['%@123abcd'])))

[1]


In [1]:
import dill